export const FETCH_STORES = "FETCH_STORES";
export const FETCH_STORES_SUCCESS = "FETCH_STORES_SUCCESS";
export const FETCH_STORES_FAILED = "FETCH_STORES_FAILED";
export const GET_LOCATION_USER = "GET_LOCATION_USER";