export const FETCH_INFORMATION_STORE = "FETCH_INFORMATION_STORE";
export const FETCH_INFORMATION_STORE_SUCCESS = "FETCH_INFORMATION_STORE_SUCCESS";
export const FETCH_INFORMATION_STORE_FAILED = "FETCH_INFORMATION_STORE_FAILED";


export const FETCH_RATING_STORE = "FETCH_RATING_STORE";
export const FETCH_RATING_STORE_SUCCESS = "FETCH_RATING_STORE_SUCCESS";
export const FETCH_RATING_STORE_FAILED = "FETCH_RATING_STORE_FAILED";

export const FETCH_PROMOTIONS_STORE = "FETCH_PROMOTIONS_STORE";
export const FETCH_PROMOTIONS_STORE_SUCCESS = "FETCH_PROMOTIONS_STORE_SUCCESS";
export const FETCH_PROMOTIONS_STORE_FAILED = "FETCH_PROMOTIONS_STORE_FAILED";

export const FETCH_SEARCH = "FETCH_SEARCH";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILED = "FETCH_SEARCH_FAILED";