export const FAVORITE = "FAVORITE";
export const FETCH_PROMOTIONS = "FETCH_PROMOTION";
export const FETCH_PROMOTIONS_SUCCESS = "FETCH_PROMOTION_SUCCESS";
export const FETCH_PROMOTIONS_FAILED = "FFETCH_PROMOTION_FAILED";
export const FETCH_TOP_PROMOTIONS = "FETCH_TOP_PROMOTIONS";
export const FETCH_TOP_PROMOTIONS_SUCCESS = "FETCH_TOP_PROMOTIONS_SUCCESS";
export const FETCH_TOP_PROMOTIONS_FAILED = "FFETCH_TOP_PROMOTIONS_FAILED";