export const FETCH_STORES = "FETCH_STORES";
export const FETCH_STORES_SUCCESS = "FETCH_STORES_SUCCESS";
export const FETCH_STORES_FAILED = "FETCH_STORES_FAILED";
export const GET_LOCATION_USER = "GET_LOCATION_USER";

export const FETCH_ALL_STORES = "FETCH_ALL_STORES";
export const FETCH_ALL_STORES_SUCCESS = "FETCH_ALL_STORES_SUCCESS";
export const FETCH_ALL_STORES_FAILED = "FETCH_ALL_STORES_FAILED";