export const FAVORITE = "FAVORITE";

export const FETCH_PROMOTIONS = "FETCH_PROMOTION";
export const FETCH_PROMOTIONS_SUCCESS = "FETCH_PROMOTION_SUCCESS";
export const FETCH_PROMOTIONS_FAILED = "FFETCH_PROMOTION_FAILED";
export const FETCH_TOP_PROMOTIONS = "FETCH_TOP_PROMOTIONS";
export const FETCH_TOP_PROMOTIONS_SUCCESS = "FETCH_TOP_PROMOTIONS_SUCCESS";
export const FETCH_TOP_PROMOTIONS_FAILED = "FFETCH_TOP_PROMOTIONS_FAILED";


export const FETCH_DETAIL_PROMOTION = "FETCH_DETAIL_PROMOTION";
export const FETCH_DETAIL_PROMOTION_SUCCESS = "FETCH_DETAIL_PROMOTION_SUCCESS";
export const FETCH_DETAIL_PROMOTION_FAILED = "FETCH_DETAIL_PROMOTION_FAILED";

export const FETCH_COMMENT_PROMOTION = "FETCH_COMMENT_PROMOTION";
export const FETCH_COMMENT_PROMOTION_SUCCESS = "FETCH_COMMENT_PROMOTION_SUCCESS";
export const FETCH_COMMENT_PROMOTION_FAILED = "FETCH_COMMENT_PROMOTION_FAILED";

